### register !!!! done
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
"email":"nhafdgn@gmail.com",
"username": "nhdfgdfgan",
"password": "1234"
}

###login !!! done
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"nhan@gmail.com",
    "password": "12345"
}

### send friend request
POST  http://localhost:3000/api/friend/sendreq
Content-Type: application/json

{
    "userId": "61c271b52b0f4301b735a33d",
    "friendId": "61c275d7cb85f50e673d6a0f"
}

### unsend friend request
POST  http://localhost:3000/api/friend/unsend
Content-Type: application/json

{
    "userId": "61c271b52b0f4301b735a33d",
    "friendId": "61c275d7cb85f50e673d6a0f"
}

### accept a friend request
POST  http://localhost:3000/api/friend/accept
Content-Type: application/json

{
    "userId": "61c275d7cb85f50e673d6a0f",
    "friendId": "61c271b52b0f4301b735a33d"
}

### decline a friend request
POST  http://localhost:3000/api/friend/decline
Content-Type: application/json

{
    "userId": "61c275d7cb85f50e673d6a0f",
    "friendId": "61c271b52b0f4301b735a33d"
}

### unfriend
POST  http://localhost:3000/api/friend/unfriend
Content-Type: application/json

{
    "userId": "61c275d7cb85f50e673d6a0f",
    "friendId": "61c271b52b0f4301b735a33d"
}

### send two userId and return conversationId, create new one if not exist
POST http://localhost:3000/api/conversation/create
Content-Type: application/json

{
    "userId": "61c271b52b0f4301b735a33d",
    "friendId": "61c275d7cb85f50e673d6a0f"
}

### get all conversation of user
POST http://localhost:3000/api/conversation/getconvs
Content-Type: application/json

{
    "userId": "61c271b52b0f4301b735a33d"
}

### get one conversation
POST http://localhost:3000/api/conversation/get
Content-Type: application/json

{
    "userId": "61c271b52b0f4301b735a33d",
    "conversationId": "61c27b1dbe203ff723d7dd9b"
}

### create a new message
POST http://localhost:3000/api/message/create
Content-Type: application/json

{
    "userId": "61c275d7cb85f50e673d6a0f",
    "conversationId":"61c27b1dbe203ff723d7dd9b",
    "content":"toi khogn biest"
}

### unsend a message
POST http://localhost:3000/api/message/unsend
Content-Type: application/json

{
    "userId": "61c275d7cb85f50e673d6a0f",
    "messageId":"61c81c9709601200c224a5e0"
}

### delete a message
POST http://localhost:3000/api/message/delete
Content-Type: application/json

{
    "userId": "61c275d7cb85f50e673d6a0f",
    "messageId":"61c81c9709601200c224a5e0"
}

### create groupconversation
POST http://localhost:3000/api/group/conversation/create
Content-Type: application/json

{
    "name": "groupchat",
    "members": ["61c2b42177efb03d08b9031f", "61c2b4ae4818a8dcd2d6abd9"]
}

### get a groupconversation
POST http://localhost:3000/api/group/conversation/get
Content-Type: application/json

{
    "conversationId": "61c6b423b2f94fef6d8bb227"
}

### add users to conversation
POST http://localhost:3000/api/group/conversation/addusers
Content-Type: application/json

{
    "conversationId": "61c6b13204fb37f7a24daa78",
    "members": ["61c2b42177efb03d08b9031f", "61c295ecd139be1761984a2a"]
}


### get all groupconversation of a user
POST http://localhost:3000/api/group/conversation/getconvs
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f"
}

### delete some users in groupconversation
POST http://localhost:3000/api/group/conversation/deleteusers
Content-Type: application/json

{
    "conversationId": "61c6b420b2f94fef6d8bb222",
    "members": ["61c2b4ae4818a8dcd2d6abd9"]
}


### delete a groupconversation
POST http://localhost:3000/api/group/conversation/delete
Content-Type: application/json

{
    "conversationId": "61c6b13204fb37f7a24daa78"
}

### create a groupmessage
POST http://localhost:3000/api/group/message/create
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "conversationId": "61c6b423b2f94fef6d8bb227",
    "content": "mot hai ba"
}

### get all messages of a groupconversation
POST http://localhost:3000/api/group/message/get
Content-Type: application/json

{
    "userId": "61c2b4ae4818a8dcd2d6abd9",
    "conversationId": "61c6b423b2f94fef6d8bb227"
}

### unsend a groupmessages
POST http://localhost:3000/api/group/message/unsend
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "messageId": "61c72148f05ccccd2a7a61b4"
}


### delete a groupmessages
POST http://localhost:3000/api/group/message/delete
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "messageId": "61c6c66701f25246f6445b2b"
}


### create post
POST http://localhost:3000/api/post/create
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "content": "sdkfjahskdfjh"
}

### get post
POST http://localhost:3000/api/post/get
Content-Type: application/json

{
    "postId": "61c53a4f142cff9120377a3f"
}

### edit post
POST http://localhost:3000/api/post/update
Content-Type: application/json

{
    "postId": "61c53a4f142cff9120377a3f",
    "content": "Một hai ba bốn"
}

### delete post
POST http://localhost:3000/api/post/delete
Content-Type: application/json

{
    "postId": "61c53a4f142cff9120377a3f"
}

### create comment
POST http://localhost:3000/api/comment/create
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "postId": "61c53a4f142cff9120377a3f",
    "content": "sdkfjahskdfjh"
}


### get comment
POST http://localhost:3000/api/comment/get
Content-Type: application/json

{
    "postId": "61c53a4f142cff9120377a3f"
}

### edit comment
POST http://localhost:3000/api/comment/update
Content-Type: application/json

{
    "commentId": "61c53fa391da473275df5955",
    "content": "Một hai ba bốn"
}

### delete comment
POST http://localhost:3000/api/comment/delete
Content-Type: application/json

{
    "commentId": "61c53fa391da473275df5955"
}

### create deadline
POST http://localhost:3000/api/deadline/create
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "deadline": "hoan thanh bai tap 2",
    "deadlinedate": "2000-11-10",
    "teacher": "Danh",
    "note": "Chia ra 3 file"
}

### get all deadline of a user
POST http://localhost:3000/api/deadline/get
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f"
}


### change deadline
POST http://localhost:3000/api/deadline/update
Content-Type: application/json

{
    "deadlineId": "61c6957f6d5b13cb72bc311e",
    "userId": "61c2b42177efb03d08b9031f",
    "deadline": "hoan thanh bai tap1",
    "deadlinedate": "2000-11-10",
    "completed": true,
    "teacher": "Danh",
    "note": "Chia ra 4 file"
}


### delete deadline
POST http://localhost:3000/api/deadline/delete
Content-Type: application/json

{
    "userId": "61c2b42177efb03d08b9031f",
    "deadlineId": "61c719b2a45659c5e89261dc"
}


### get image
GET http://localhost:3000/api/image/df7602a8-2aef-4f9c-a1cc-a13d9d7363ac.png
Content-Type: application/json

{
    
}


